### ISSUE TITLE
Pesquisar por um sistema similar

### ISSUE THREAD

**Issue by RicardoCA** [RicardoCA/Napolis#12]

**Comment by RicardoCA** [comment]
Entrando no google para buscar por um sistema similar.

**Comment by ghost** [comment]
Este link do Sebrae contribui.
http://www.sebrae.com.br/sites/PortalSebrae/ideias/Como-montar-uma-pizzaria
Também link próprio como Cartão de Visita contendo Cardápio, Telefone e Endereço.

**Comment by RicardoCA** [comment]
Encontrei um sistema gratuito para pizzaria, estou baixando para teste.
