### ISSUE TITLE
Desenvolver cenário (Gerar Relatórios) de casos de uso.

### ISSUE THREAD

**Issue by RicardoCA** [RicardoCA/Napolis#15]
Pegar o documento do astah, e desenvolver o cenário com os testes, e entradas de dados.

**Comment by ghost** [comment]
![usecasepizzariaalacarte](https://cloud.githubusercontent.com/assets/5138264/7653630/8c61a20a-faed-11e4-8ad8-70296423e7d7.jpg)

**Comment by RicardoCA** [comment]
Foram desenvolvidos somente o caso de uso, mas não o cenário.
