### ISSUE TITLE
Configurar ambiente no computador do Eduardo.

### ISSUE THREAD

**Issue by edutaiji** [RicardoCA/Napolis#2]

**Comment by masmangan** [comment]
Dados do proxy na minha conta.
.gitconfig
[http]
proxy = http://192.168.0.1:8080
[https]
proxy = https://192.168.0.1:8080

No computador do Eduardo, criar um arquivo com o nome .gitconfig.

**Comment by Ravelliserpa** [comment]
Colocar arquivo .gitconfig na pasta do usuario, e usar o comando:
cat .gitconfig
No Git Bash, para finalizar a conclusão.
