### ISSUE TITLE
Reorganizar pastas da implementação

### ISSUE THREAD

**Issue by masmangan** [RicardoCA/Napolis#38]
Criar repositório paralelo (fork)
Remover zip.
Organizar código fonte.
Apagar pastas da implementação que estejam desatualizadas.
Criar Wiki com instruções para importar e exportar projeto do NetBeans.

**Comment by Ravelliserpa** [comment]
Commitado errado com "38" ao invez de "#38".

**Comment by Ravelliserpa** [comment]
Link da Wiki Feita deste Ticket:
[Instruções para importar e exportar projeto do NetBeans.](https://github.com/RicardoCA/Napolis/wiki/Instru%C3%A7%C3%B5es-para-importar-e-exportar-projeto-do-NetBeans.)
