### ISSUE TITLE
Realização de caso de uso: Consultar funcionários

### ISSUE THREAD

**Issue by masmangan** [RicardoCA/Napolis#42]
Abrir repositório paralelo (fork).

Desenvolver visão, modelo de caso e caso uso.
(Revisar os documentos existentes.)
Desenvolver classes de análise e de projeto.
(Criar dois diagramas no Astah. Com bolinhas e com classes.)
Gerar código no Eclipse.
(De preferência, utilizar geração de código do Astah.)
Criar demonstração funcional.
(Tela no Window Builder e criar .jar)

**Comment by raphaelbl** [comment]
modificado vision descriçao gerente, e classes consultar funcionario em astah + criaçao .jar
